/**
 * Static slug → Firestore docId map, generated from data/cases.json.
 * Resolving a slug to a docId no longer requires a Firestore query —
 * it's an instant O(1) map lookup that works offline and before auth.
 *
 * Update this file (or re-run the generator) whenever a new case is added:
 *   node -e "
 *     const d = require('./data/cases.json');
 *     const slugify = t => String(t).toLowerCase().trim()
 *       .replace(/['’]/g,'').replace(/&/g,'and')
 *       .replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
 *     const m = {};
 *     d.forEach(c => { m[c.slug || slugify(c.title)] = c.docId; });
 *     console.log(JSON.stringify(m, null, 2));
 *   "
 */
export const SLUG_TO_DOC_ID: Record<string, string> = {
  "banking-on-you": "case-1",
  "dry-hard": "case-2",
  "oil-be-there-for-you": "case-3",
  "hotel-california": "case-4",
  "chip-o-tale": "case-5",
  "max-problems-at-mini-so": "case-6",
  "critical-condition": "case-7",
  "take-me-to-the-candy-shop": "case-8",
  "mall-of-fame": "case-9",
  "make-up-for-lost-profits": "case-10",
  "greys-anatomy": "case-11",
  "i-knew-you-were-trouble-when-i-walked-in": "case-12",
  "habibi-come-to-dubai": "case-13",
  "as-you-sow-so-shall-you-reap": "case-14",
  "dont-sweat-it": "case-15",
  "charlie-and-the-candy-factory": "case-16",
  "look-ma-i-can-fly": "case-17",
  "terrible-times": "case-18",
  "empty-kart": "case-19",
  "pulp-fiction": "case-20",
  "death-by-chocolate": "case-21",
  "dont-steel-from-us": "case-22",
  "my-milkshake-brings-all-the-boys-to-the-yard": "case-23",
  "the-king-of-bad-times": "case-24",
  "beauty-lies-on-the-inside": "case-25",
  "fields-of-gold": "case-26",
  "iim-a-irtel": "case-27",
  "hotline-bling": "case-28",
  "jab-we-met": "case-29",
  "the-sun-wont-set-on-us": "case-30",
  "testing-the-waters": "case-31",
  "pound-for-pound": "case-32",
  "mr-worldwide": "case-33",
  "sicko-mode": "case-34",
  "wat-uh-product": "case-35",
  "ferry-tales": "case-36",
  "when-life-gives-you-lemons": "case-37",
  "when-chai-met-toast": "case-38",
  "netflix-and-chill": "case-39",
  "the-hunger-games": "case-40",
  "parts-and-recreation": "case-41",
  "udta-punjab": "case-42",
  "risk-it-for-the-biscuit": "case-43",
  "variety-is-the-spice-of-life": "case-44",
  "deloitted-to-meet-you": "case-45",
  "paint-the-town-red": "case-46",
  "raise-the-bar": "case-47",
  "chasing-cars": "case-48",
  "fly-me-to-the-moon": "case-49",
  "up-in-the-air": "case-50",
  "make-india-great-again": "case-51",
  "mo-money-mo-problems": "case-52",
  "gold-digger": "case-53",
  "rating-neil-nitin-and-mukesh": "case-54",
  "left-me-high-and-dry": "case-55",
  "zero-dark-thirty": "case-56",
  "panel-discussion": "case-57",
  "ups-and-downs": "case-58",
  "young-poets-society": "case-59",
  "an-apple-a-day-keeps-the-doctor-away": "case-60",
  "bad-teacher": "case-61",
  "houston-we-have-a-problem": "case-62",
  "crash-course": "case-63",
  "take-me-to-mosque": "case-64",
  "cash-me-if-you-can": "case-65",
  "wired-differently": "case-66",
  "the-godfather": "case-67",
  "wheres-perry": "case-68",
  "finding-bambi": "case-69",
  "dallas-buyers-club": "case-70",
  "house-of-cards": "case-71",
  "net-worth": "case-72",
  "tip-tip-barsa-paani": "case-73",
  "padhega-india-badhega-india": "case-74",
  "money-heist": "case-75",
  "hala-madrid": "case-76",
  "subway-surfers": "case-77",
  "dont-do-coke": "case-78",
  "its-lights-out-and-away-we-go": "case-79",
  "lights-will-guide-you-home": "case-80",
  "my-name-is-khan": "case-81",
  "space-from-my-x": "case-82",
  "once-upon-a-timesheet": "case-83",
  "final-destination": "case-84",
  "no-of-fence": "case-85",
  "waddle-we-eat": "case-86",
  "mile-high-club": "case-87",
  "home-alone": "case-90",
}
